### ISSUE TITLE
RouterModel.create breaks on mobx-state-tree@3.9.0

### ISSUE THREAD

**Issue by jadbox** [alisd23/mst-react-router#16]
Upon updating to mobx-state-tree@3.9.0:

```
/src/index.tsx
Type error: Argument of type 'null' is not assignable to parameter of type 'ExtractCFromProps<RequiredPropsObject<ModelPropertiesDeclarationToProperties<Props>> & OptionalPropsObject<ModelPropertiesDeclarationToProperties<Props>>>'.  TS2345

    15 | 
    16 | // Setup History
  > 17 | const routerModel = RouterModel.create();
```

**Comment by jadbox** [comment]
See line 5 in for the Model field that should be optional for create() construction:
https://github.com/alisd23/mst-react-router/blob/master/src/store.js

I think this might be a MST bug.. posted bug report:
https://github.com/mobxjs/mobx-state-tree/issues/1102

**Comment by jadbox** [comment]
See this comment on the fix needed: https://github.com/mobxjs/mobx-state-tree/issues/1102#issuecomment-445161397

**Comment by alisd23** [comment]
Interesting, and thanks for opening the issue and getting getting the answers. Looks like that comment is correct, changing the model `Props` type to:

```
type Props = {
  location: IOptionalIType<IType<Location, Location, Location>>;
  action: string;
}
```

fixes it for me.

**Comment by alisd23** [comment]
Please post on here if this fix doesn't resolve it or if it causes other issues 👍
