### ISSUE TITLE
RouterModel.create( ) breaks with MST@3.11.0

### ISSUE THREAD

**Issue by harry-sm** [alisd23/mst-react-router#18]
The create method now requires a parameter. Seems like types.optional have been modified. See https://github.com/mobxjs/mobx-state-tree/blob/master/changelog.md#3110

**Comment by marcofugaro** [comment]
yes, for now you can solve it with `RouterModel.create({ location: {} })`

**Comment by harry-sm** [comment]
@marcofugaro 
That didn't work for me. When I did that I couldn't use the location object with type safety.
`router.location.pathname`
`Property 'pathname' does not exist on type.`

**Comment by alisd23** [comment]
Not using this library at the moment at work, and am very short of time at the moment, so I probably won't be able to look at this properly for a while. 

Would be great if someone could take a look and put up a PR for this, if anyone wants this fixed more urgently. The codebase for this library is quite small 👍

**Comment by marcofugaro** [comment]
Probably related to this other issue:
https://github.com/mobxjs/mobx-state-tree/issues/1208

It's better to wait for it to be solved

**Comment by harry-sm** [comment]
I took the router store and modified it by adding a location model

```js
const LocationModel = types.model({
   key: types.maybe(types.string),
   pathname: types.maybe(types.string),
   search: types.maybe(types.string),
   hash: types.maybe(types.string),
   state: types.frozen()
});

export const RouterModel = types
   .model('RouterModel', {
      location: types.optional(LocationModel, {}),
      action: types.optional(types.string, '')
   })
```

**Comment by freund17** [comment]
I'm about 99.99 % (+/- 0.01 %) sure, this is because of https://github.com/mobxjs/mobx-state-tree/pull/1192/files#diff-22a2e46c43156dfa47bc67f7bb4c073f.

Updating line 10 in `types.d.ts` from

```ts
    location: IOptionalIType<IType<Location, Location, Location>>;
```

to the new `IOptionalIType`:

```ts
    location: IOptionalIType<IType<Location, Location, Location>, [undefined]>;
```

fixes the problem.
I can create a PR, but it will most likely be a breaking change for everyone using mst@<3.11.0.

**Comment by harry-sm** [comment]
I Kinda just "borrowed"  the code and created a location model
```ts
const LocationModel = types.model({
	key: types.maybe(types.string),
	pathname: types.maybe(types.string),
	search: types.maybe(types.string),
	hash: types.maybe(types.string),
	state: types.frozen()
});

const RouterModel = types
	.model('RouterModel', {
		location: types.optional(LocationModel, {}),
		action: types.optional(types.string, '')
	})
```

**Comment by harry-sm** [comment]
@alisd23 Would you be open to a rewrite in typescript?

**Comment by nfour** [comment]
@harry-sm 

```ts
/** This module is copy pasted and fixed from `mst-react-router` as the project is unmaintained */

import { History } from 'history';
import { reaction } from 'mobx';
import { types } from 'mobx-state-tree';

export const RouterModel = types
  .model('RouterModel', {
    location: types.optional(types.frozen(), {}),
    action: '',
  })
  .actions((self) => {
    // "volatile" state to store history instance from "history" library
    let history: History;

    return {
      _updateLocation(location: typeof self['location']) {
        self.location = location;
        self.action = history.action;
      },
      _setHistory(initialHistory: History) {
        history = initialHistory;
      },
      push(...args: Parameters<typeof history['push']>) {
        history.push(...args);
      },
      replace(...args: Parameters<typeof history['replace']>) {
        history.replace(...args);
      },
      go(...args: Parameters<typeof history['go']>) {
        history.go(...args);
      },
      goBack() {
        history.goBack();
      },
      goForward() {
        history.goForward();
      },
      block(...args: Parameters<typeof history['block']>) {
        history.block(...args);
      },
    };
  });

/**
 * Sync the history object with the given mst router store
 *
 * @param history - 'History' instance to subscribe and sync to
 * @param routerStore - Router store instance to sync with the history changes
 */
export const syncHistoryWithStore = (history: History, routerStore: typeof RouterModel.Type) => {
  routerStore._setHistory(history);

  function isLocationEqual(locationA: any, locationB: any) {
    return locationA && locationB && locationA.key && locationB.key && locationA.key === locationB.key;
  }

  // Handle update from history object
  const handleLocationChange = (location: any) => {
    if (!isLocationEqual(routerStore.location, location)) {
      routerStore._updateLocation({ ...location });
    }
  };

  const unsubscribeFromHistory = history.listen(handleLocationChange);
  const unsubscribeFromStoreLocation = reaction(
    () => routerStore.location,
    (location) => {
      if (!isLocationEqual(history.location, location)) {
        history.replace({ ...location });
      }
    },
  );

  handleLocationChange(history.location);

  function unsubscribe() {
    unsubscribeFromHistory();
    unsubscribeFromStoreLocation();
  }

  return { unsubscribe, unsubscribeFromHistory, unsubscribeFromStoreLocation, history };
};

```

Updated to TS and now just import it from a file because it's so tiny.

Feel free to turn into an npm module.

**Comment by alisd23** [comment]
Sorry for the delay, have had no time recently to commit to this project.
I've merged in the related PR. If any other changes are need feel free to open a PR.

**On a general note:**
I will have even less time moving forward to work on this project, so I'm more than happy to add maintainers (or transfer - is that a thing?) to people who are using this reguarly. Let me know if you're interested 👍

**Comment by alisd23** [comment]
> @alisd23 Would you be open to a rewrite in typescript?

And yes sure, but see above message

**Comment by Krivega** [comment]
@alisd23  there was no release with the latest changes, could you publish it in npm?

**Comment by nfour** [comment]
> @alisd23 there was no release with the latest changes, could you publish it in npm?

Try https://github.com/nfour/xroute
