### ISSUE TITLE
Is it possible to update React Router's location when using Time Traveling?

### ISSUE THREAD

**Issue by jonavila** [alisd23/mst-react-router#3]
Hi

I'm trying to use mobx-devtools-mst to do time traveling and when the RouterModel location is changed by the devtools, it doesn't update the React Router's location. Does the synchronization only work one way from React Router to the MST RouterModel, but not the other way around?

**Comment by alisd23** [comment]
Hi, currently this library does not support time-travelling.

The synchronization is actually two-way (history changes update store, and router store actions update history), but you can only update the history via the router store actions.

The solution would consist of something like subscribing to the router store, listening for changes in the location, then updating the history (through a `push` or `replace` - not sure which one would be better).

It's a slightly strange one as although the **router store** will be time-travelling, the **browser history** will not be time-travelling, as location changes in the store will just have to push or replace the new location onto history, creating this strange inconsistency between the 2.

If anyone wants to give this a crack in a PR that would be great - then we can discuss the potential solution further.

**Comment by Keyj1n** [comment]
if im not wrong, when timetraveling a new snapshot will be applied to the store. So we can use preProcessSnapshot in the store and replace the old location with the new one.

`.preProcessSnapshot(snapshot => {
    snapshot.replace(snapshot.location)
    return snapshot;
  });
`

**Comment by alisd23** [comment]
This seems promising. Though the docs say this about `.preProcessSnapshot`:
> "can be used to pre-process the raw JSON before instantiating a new model"

So I'm not sure if you could get access to the router model in this function and call `.replace(...)`.

**Comment by freund17** [comment]
I think `preProcessSnapshot` is not the right call here...
It seems to be meant to be used to, well, pre-process snapshots...

Also using `preProcessSnapshot` would mean that the logic for syncing the store to the history would lie in `store.js`, when it would make more sense to have it in `sync.js`.

`syncHistoryWithStore` seems to be the correct place for this.

In my implementation I used [reaction](https://mobx.js.org/refguide/reaction.html) to detect the store-change.
To prevent an infinite loop, the location is only updated (either on the store or the history-api), when it differs from what is already there.

Two locations are different, when
  - one or both of them are Falsely
  - the "key"-value on one or both of them are Falsely
  - the "key"-values aren't strict equal

In the store, only "location" is watched, not "action".
When the location changes in the store, the history is always replaced.
