### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by jadbox** [alisd23/mst-react-router#4]
It would be great to have a bindings file.

**Comment by alisd23** [comment]
That would be a good addition.
I'm open to any PR's adding a `types.d.ts` file - not sure when I'll next have time to look into it.

**Comment by Keyj1n** [comment]
I created an PR.

**Comment by alisd23** [comment]
Closed with #5

**Comment by alisd23** [comment]
Version `1.1.1` has now been released with these typings. Thanks to @Keyj1n for writing these.
